"""
make_mirage_configs.py

Generate TrajFlow config YAML files for MIRAGE baseline.

Usage:
    python scripts/make_mirage_configs.py --city NewYork
    python scripts/make_mirage_configs.py --city Tokyo
    python scripts/make_mirage_configs.py --city Istanbul
    python scripts/make_mirage_configs.py --all

Output:
    src/config/config_mirage_{city_lower}.yaml
"""

import argparse
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
TRAJFLOW_ROOT = (SCRIPT_DIR / "..").resolve()
CONFIG_DIR = TRAJFLOW_ROOT / "src" / "config"


TEMPLATE = """# Auto-generated config for MIRAGE baseline — {city}
# Generated by scripts/make_mirage_configs.py
project:
  name: trajflow_mirage_{city_lower}
  output_dir: ./outputs/mirage_baseline/{city}/train
  seed: 42

data:
  dataset_type: didi
  region: {city}
  dataset_folder: data/mirage_trajflow/{city}
  sample_count: -1           # load all available samples
  trajectory_length: 120
  batch_size: 256
  parametrized: true
  parametrized_method: rdp_k
  parametrized_M: 10
  norm1by1: true
  od_finer: false           # geohash OD only, no jismesh
  geohash: true            # enable geohash decoding in inference.py
  geohash_precision: 6
  split_mode: mirage
  train_split_file: data/mirage_trajflow/{city}/train_val_indices.pkl
  test_split_file: data/mirage_trajflow/{city}/test_indices.pkl

flow_matching:
  enabled: true
  dropout_prob: 0.1
  flow_type: standard

ddpm:
  enabled: false
  beta_schedule: linear
  beta_start: 0.000001
  beta_end: 0.05
  num_diffusion_timesteps: 300
  ddim_steps: 300

condition:
  enabled: true
  condition_type: full
  transportation_mode: true
  embedding_type: wide_and_deep
  cfg_scale: 1

model:
  type: unet
  hidden_dim: 512

training:
  num_epochs: 50
  learning_rate: 0.0001
  print_every: 100
  save_every: 500
  viz_bool: false
  early_stop_patience: 50
  early_stop_delta: 0.000001
  device: cuda:0

solver:
  method: euler
  step_size: 0.01

inference:
  num_samples: 200
  num_steps: 10
  sampling_method: em

visualization:
  num_samples: 200
  create_gif: false
  fps: 2
  norm1by12origialvis: true

unet:
  type: bayesian
  guidance_scale: 3
  in_channels: 2
  out_ch: 2
  ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.1
  var_type: fixedlarge
  ema_rate: 0.9999
  ema: true
  resamp_with_conv: true
  grid_dim: 512

baseline:
  enabled: false
  type: markov
"""


def make_config(city):
    city_lower = city.lower()
    config_path = CONFIG_DIR / f"config_mirage_{city_lower}.yaml"
    content = TEMPLATE.format(city=city, city_lower=city_lower)
    with open(config_path, 'w') as f:
        f.write(content)
    print(f"  {config_path}")
    return config_path


def main():
    parser = argparse.ArgumentParser(description="Generate MIRAGE config YAML files.")
    parser.add_argument('--city', type=str, choices=['NewYork', 'Tokyo', 'Istanbul'])
    parser.add_argument('--all', action='store_true', help='Generate all three cities')
    args = parser.parse_args()

    cities = []
    if args.all:
        cities = ['NewYork', 'Tokyo', 'Istanbul']
    elif args.city:
        cities = [args.city]
    else:
        parser.print_help()
        return

    print(f"\nGenerating config files:")
    for city in cities:
        config_path = make_config(city)
        print(f"  Wrote: {config_path}")

    print("\nDone. Next steps:")
    print("  1. python scripts/prepare_mirage_trajflow_data.py --city {CITY}")
    print("  2. python train.py --config src/config/config_mirage_{city_lower}.yaml")
    print("  3. python generate.py --config src/config/config_mirage_{city_lower}.yaml ...")
    print("  4. python scripts/postprocess_mirage_trajflow_generated.py --city {CITY}")
    print("  5. python scripts/evaluate_mirage_5d.py --city {CITY}")


if __name__ == '__main__':
    main()
